[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gl = "0.14.0"
glfw = "0.43.0"
winit = "0.26.1"